projekat/WebApp/Controllers/AutorskaPravaController.cs
using System.Drawing;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using Business.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PdfSharp;
using VDS.RDF;
using VDS.RDF.Writing;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize]
    public class AutorskaPravaController : Controller
    {
        private readonly ApiClient _apiClient;
        private static AutorskoPravoModel AutorskoPravo { get; set; }

        public AutorskaPravaController(ApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public IActionResult Index(string? pojam, bool metadataSearch, int searchType, string PodnosilacDetalji,
                                    string operatorPodnosilacDetalji,
                                    string Telefon, string operatorTelefon, string Email, string operatorEmail,
                                    string Pseudonim, string operatorPseudonim, string Punomocnik, string operatorPunomocnik,
                                    string Naslov, string operatorNaslov, string PodaciONaslovu, string operatorPodaciONaslovu,
                                    string PodaciOVrsti, string operatorPodaciOVrsti, string PodaciOFormiZapisa,
                                    string operatorPodaciOFormiZapisa, string PodaciOAutoru, string operatorPodaciOAutoru,
                                    string DaLiJeURadnomODnosu, string operatorDaLiJeURadnomODnosu,
                                    string NacinKoriscenja, string operatorNacinKoriscenja, string PodnosilacPrijavePotpis, string operatorPodnosilacPrijavePotpis, DateTime? DatumPodnosenja, string operatorDatumPodnosenja, bool? Zaveden, string operatorZaveden, string Status,
                                    string operatorStatus, string FajloviPutanje, string operatorFajloviPutanje)
        {

            var isUserAdmin = User.IsInRole("Admin");

            var userName = User.Identity.Name;

            List<AutorskoPravoModel> prijave = new List<AutorskoPravoModel>();
            if (metadataSearch)
            {
                var autorskoPravoModel = new AutorskoPravoModel
                {
                    PodnosilacDetalji = PodnosilacDetalji ?? "",
                    Telefon = Telefon ?? "",
                    Email = Email ?? "",
                    Pseudonim = Pseudonim ?? "",
                    Punomocnik = Punomocnik ?? "",
                    Naslov = Naslov ?? "",
                    PodaciONaslovu = PodaciONaslovu ?? "",
                    PodaciOVrsti = PodaciOVrsti ?? "",
                    PodaciOFormiZapisa = PodaciOFormiZapisa ?? "",
                    PodaciOAutoru = PodaciOAutoru ?? "",
                    DaLiJeURadnomODnosu = DaLiJeURadnomODnosu ?? "",
                    NacinKoriscenja = NacinKoriscenja ?? "",
                    PodnosilacPrijavePotpis = PodnosilacPrijavePotpis ?? "",
                    DatumPodnosenja = DatumPodnosenja.HasValue ? DatumPodnosenja.Value : default,
                    Zaveden = Zaveden.HasValue ? Zaveden.Value : false,
                    SearchType = (SearchType)searchType,
                    IsAdmin = isUserAdmin,
                    User = userName
                };

                prijave = _apiClient.PretragaMetapodaci(autorskoPravoModel).Result;
            }
            else
            {
                prijave = !string.IsNullOrEmpty(pojam) ?
                _apiClient.PretraziPrijave(pojam, isUserAdmin, userName).Result : _apiClient.VratiSvePrijave(isUserAdmin, userName).Result;

                ViewBag.Pojam = pojam;
            }

            return View(prijave);
        }


        public IActionResult MetadataSearch()
        {
            var isUserAdmin = User.IsInRole("Admin");

            List<AutorskoPravoModel> prijave = !string.IsNullOrEmpty("") ?
            _apiClient.PretraziPrijave("", isUserAdmin, User.Identity.Name).Result : _apiClient.VratiSvePrijave(isUserAdmin, User.Identity.Name).Result;

            ViewBag.Pojam = "";

            return View(prijave);
        }

        public IActionResult Prijava(int id)
        {
            AutorskoPravoModel prijava = _apiClient.VratiPrijavu(id).Result;

            AutorskoPravo = prijava;

            return View(prijava);
        }

        private static List<string> CurrentFilePaths = new List<string>();

        [HttpPost]
        public async Task<IActionResult> UploadFiles(IList<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);
            var fileNameTemp = GetRandomString(5);

            var filePaths = new List<string>();
            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    var filePath = $@"C:\autorskaprava\{fileNameTemp}_{formFile.FileName}";

                    filePaths.Add(filePath);
                    CurrentFilePaths.Add(filePath);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            return Ok();
        }

        private static string GetRandomString(int length)
        {
            Random random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }


        public IActionResult NovaPrijava()
        {
            return View();
        }

        [HttpPost]
        public AutorskoPravoModel NovaPrijava(AutorskoPravoModel prijava)
        {
            prijava.FajloviPutanje = CurrentFilePaths;
            prijava.Pdf = "";
            prijava.Sifra = "";

            prijava.User = User.Identity.Name;

            AutorskoPravoModel kreiranaPrijava = _apiClient.NovaPrijava(prijava).Result;

            CurrentFilePaths = new List<string>();
            return kreiranaPrijava;
        }

        [HttpPost]
        public bool PodnesiResenje(ResenjeModel resenje)
        {
            if (string.IsNullOrEmpty(resenje.ObrazlozenjeOdbijanja))
                resenje.ObrazlozenjeOdbijanja = string.Empty;

            var nameIdentifier = User.Claims.FirstOrDefault(x => x.Type.Contains("nameidentifier"));

            resenje.UserId = nameIdentifier?.Value;

            var filePath = Path.Combine(@"C:\autorskaprava\zahtevi", $"{AutorskoPravo.Naslov}.pdf");

            KreirajPdf(filePath);

            resenje.PdfFile = filePath ?? string.Empty;

            string domainPath = Request.Scheme + "://" + Request.Host;

            resenje.Referenca = domainPath + resenje.Referenca;

            bool resenjeResult = _apiClient.PodnesiResenje(resenje).Result;

            return resenjeResult;
        }


        public IActionResult DownloadMetadataRdf()
        {
            var graph = new Graph();

            var rdfNamespace = graph.NamespaceMap;
            rdfNamespace.AddNamespace("rdf", new Uri("http://www.w3.org/1999/02/22-rdf-syntax-ns#"));
            rdfNamespace.AddNamespace("rdfs", new Uri("http://www.w3.org/2000/01/rdf-schema#"));
            rdfNamespace.AddNamespace("ex", new Uri("http://example.org/"));

            var subjectNode = graph.CreateUriNode("ex:subject");
            graph.Assert(subjectNode, graph.CreateUriNode("rdf:type"), graph.CreateUriNode("ex:AutorskoPravo"));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:Sifra"), graph.CreateLiteralNode(AutorskoPravo.Sifra));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:PodnosilacDetalji"), graph.CreateLiteralNode(AutorskoPravo.PodnosilacDetalji));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:Telefon"), graph.CreateLiteralNode(AutorskoPravo.Telefon));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:Email"), graph.CreateLiteralNode(AutorskoPravo.Email));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:Pseudonim"), graph.CreateLiteralNode(AutorskoPravo.Pseudonim));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:Punomocnik"), graph.CreateLiteralNode(AutorskoPravo.Punomocnik));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:Naslov"), graph.CreateLiteralNode(AutorskoPravo.Naslov));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:PodaciONaslovu"), graph.CreateLiteralNode(AutorskoPravo.PodaciONaslovu));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:PodaciOVrsti"), graph.CreateLiteralNode(AutorskoPravo.PodaciOVrsti));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:PodaciOFormiZapisa"), graph.CreateLiteralNode(AutorskoPravo.PodaciOFormiZapisa));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:PodaciOAutoru"), graph.CreateLiteralNode(AutorskoPravo.PodaciOAutoru));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:DaLiJeURadnomODnosu"), graph.CreateLiteralNode(AutorskoPravo.DaLiJeURadnomODnosu));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:NacinKoriscenja"), graph.CreateLiteralNode(AutorskoPravo.NacinKoriscenja));
            graph.Assert(subjectNode, graph.CreateUriNode("ex:PodnosilacPrijavePotpis"), graph.CreateLiteralNode(AutorskoPravo.PodnosilacPrijavePotpis));

            var rdfWriter = new CompressingTurtleWriter();
            var rdfData = new System.IO.StringWriter();
            rdfWriter.Save(graph, rdfData);

            var filePath = System.IO.Path.Combine(@"C:\autorskaprava\metadata", $"{AutorskoPravo.Naslov}.rdf");
            System.IO.File.WriteAllText(filePath, rdfData.ToString());

            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            string fileN = System.IO.Path.GetFileName(filePath);
            string contentType = "application/rdf+xml";

projekat/WebApp/Views/AutorskaPrava/Index.cshtml
@using Business.Models;
@model List<AutorskoPravoModel>

@{
    var pojam = ViewBag.Pojam;
}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>Sve prijave autorskih prava</h2>
    </div>
</div>

<div class="row" style="margin-top: 50px">
    <div class="col-md-4">
        <input type="text" id="pretraziPrijaveInput" value="@pojam" class="form-control" placeholder="Pretraži prijave...">
    </div>
    <div class="col-md-1">
        <button class="btn btn-primary" onclick="AutorskoPravo.pretraziPrijave()">
            Pretraži
        </button>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#searchModal">
            Detaljna pretraga
        </button>
    </div>
    @if (User.IsInRole("Admin"))
    {
        <div class="col-md-5" style="text-align: right">
            <div class="row">
            <div class="col-md-4" style="text-align: left">
                <label for="startDate">Od</label>
                <input type="date" id="startDate" class="form-control" />
            </div>
            <div class="col-md-4" style="text-align: left">
                <label for="endDate">Do</label>
                <input type="date" id="endDate" class="form-control" />
            </div>
            <div class="col-md-4" style="margin-top: 22px">
                <button class="btn btn-success" onclick="AutorskoPravo.generisiIvestaj()">Generiši izveštaj</button>
            </div>
        </div>
    </div>
    }

</div>
<div class="row" style="margin-top: 50px">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Šifra</th>
                <th>Naslov</th>
                <th>Autor</th>
                <th>Email</th>
                <th>Podneto Datuma</th>
                <th>Status</th>
                <th>Detalji</th>
                <th>Akcija</th>
            </tr>
        </thead>
        <tbody id="svePrijavaBody">
            @foreach (var pravo in Model)
            {
                <tr>
                    <td>@pravo.Id</td>
                    <td>@pravo.Sifra</td>
                    <td>@pravo.Naslov</td>
                    <td>@pravo.PodaciOAutoru</td>
                    <td>@pravo.Email</td>
                    <td>@pravo.DatumPodnosenja.ToString()</td>
                    <td class="@(pravo.Status == Domain.Entities.Status.Odobren ? "text-success" : pravo.Status == Domain.Entities.Status.Odbijen ? "text-danger" : "text-primary")" >@pravo.Status</td>
                    <td>
                        <button class="btn btn-sm btn-primary">
                            <a href="/AutorskaPrava/Prijava?id=@pravo.Id" style="color: white;text-decoration: none">Detalji</a>
                        </button>
                    </td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="searchModalLabel">Pretraga po metapodacima</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="searchForm">
                    <div class="row">
                        <div class="col-md-12">
                            <select id="searchType" name="searchType" class="form-control" style="margin-bottom: 20px" title="Odaberi tip pretrage...">
                                <option value="0" selected>AND</option>
                                <option value="1">OR</option>
                                <option value="2">NOT</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="PodnosilacDetalji" class="form-label">Podnosilac Detalji</label>
                        <input type="text" class="form-control" id="PodnosilacDetalji" name="PodnosilacDetalji">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="Telefon" class="form-label">Telefon</label>
                        <input type="text" class="form-control" id="Telefon" name="Telefon">
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                        <label for="Email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="Email" name="Email">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="Pseudonim" class="form-label">Pseudonim</label>
                        <input type="text" class="form-control" id="Pseudonim" name="Pseudonim">
                        </div>
                    </div>
                    <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="Punomocnik" class="form-label">Punomocnik</label>
                        <input type="text" class="form-control" id="Punomocnik" name="Punomocnik">
                    </div>
                        <div class="col-md-6 mb-3">
                        <label for="Naslov" class="form-label">Naslov</label>
                        <input type="text" class="form-control" id="Naslov" name="Naslov">
                        </div>
                    </div>
                    <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="PodaciONaslovu" class="form-label">Podaci O Naslovu</label>
                        <input type="text" class="form-control" id="PodaciONaslovu" name="PodaciONaslovu">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="PodaciOVrsti" class="form-label">Podaci O Vrsti</label>
                        <input type="text" class="form-control" id="PodaciOVrsti" name="PodaciOVrsti">
                    </div>
                    </div>
                    <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="PodaciOFormiZapisa" class="form-label">Podaci O Formi Zapisa</label>
                        <input type="text" class="form-control" id="PodaciOFormiZapisa" name="PodaciOFormiZapisa">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="PodaciOAutoru" class="form-label">Podaci O Autoru</label>
                        <input type="text" class="form-control" id="PodaciOAutoru" name="PodaciOAutoru">
                    </div>
                    </div>
                    <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="DaLiJeURadnomODnosu" class="form-label">Da Li Je U Radnom Odnosu</label>
                        <input type="text" class="form-control" id="DaLiJeURadnomODnosu" name="DaLiJeURadnomODnosu">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="NacinKoriscenja" class="form-label">Nacin Koriscenja</label>
                        <input type="text" class="form-control" id="NacinKoriscenja" name="NacinKoriscenja">
                    </div>
                    </div>
                    <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="PodnosilacPrijavePotpis" class="form-label">Podnosilac Prijave Potpis</label>
                        <input type="text" class="form-control" id="PodnosilacPrijavePotpis" name="PodnosilacPrijavePotpis">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="DatumPodnosenja" class="form-label">Datum Podnosenja</label>
                        <input type="date" class="form-control" id="DatumPodnosenja" name="DatumPodnosenja">
                    </div>
                    </div>
                    <div class="col-md-6 mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="Zaveden" name="Zaveden">
                        <label class="form-check-label" for="Zaveden">Zaveden</label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="AutorskoPravo.pretraziPrijaveMetapodaci()" id="searchButton">Search</button>
            </div>
        </div>
    </div>
</div>

projekat/WebApp/Views/AutorskaPrava/NovaPrijava.cshtml
<div class="row" style="border: 1px solid black;">
    <div class="col-md-12">
        <div class="row text-center">
            <div class="col-md-6">
                <h4> ZAVOD ZA INTELEKTUALNU SVOJINU</h4>
                <h5>Beograd, Knjeginje Ljubice 5</h5>
            </div>
            <div class="col-md-6">
                <h4> OBRAZAC A-1</h4>
            </div>
        </div>
        <div class="row" style="margin-top: 50px; margin-bottom: 50px">
            <div class="col-md-12 text-center">
                <h4>ZAHTEV ZA UNOŠENJE U EVIDENCIJU I DEPONOVANJE AUTORSKIH PRAVA</h4>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <h5>1) Podnosilac - ime, prezime, adresa i državljanstvo autora ili drugog nosioca autorskog prava ako je podnosilac fizičko lice, 
                    odnosno poslovno ime i sedište nosioca autorskog prava ako je podnosilac pravno lice*:</h5>

                <textarea class="form-control" style="margin-top: 20px; height: 300px" id="podnosilacValue"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 20px">
               <div class="row">
                    <div class="col-md-5">
                        <h5 for="podnosilacTelefon">Telefon: </h5>
                        <input type="text" class="form-control" id="podnosilacTelefon" />
                    </div>
                   <div class="col-md-7">
                        <h5 for="podnosilacEmail">Email: </h5>
                        <input type="email" class="form-control" id="podnosilacEmail" />
                   </div>
               </div>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    2) Pseudonim ili znak autora, (ako ga ima):
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="pseudonimValue"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    3) Ime, prezime i adresa punomoćnika, ako se prijava podnosi preko punomoćnika:
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="punomocnikDetalji"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    4) Naslov autorskog dela, odnosno alternativni naslov, ako ga ima, po kome autorsko delo može da se identifikuje*:
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="naslovAutorskogDela"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                   5) Podaci o naslovu autorskog dela na kome se zasniva delo prerade, ako je u pitanju autorsko delo prerade, kao i podataka o autoru izvornog dela:
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="podaciONaslovuAutorskogDela"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    6) Podaci o vrsti autorskog dela (književno delo, muzičko delo, likovno delo, računarski program i dr.)*: 
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="vrstaAutorskogDela"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    7) Podaci o formi zapisa autorskog dela (štampani tekst, optički disk i slično)*: 
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="formaAutorskogDela"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    8) Podaci o autoru ako podnosilac prijave iz tačke 1. ovog zahteva nije autori i to: prezime, ime, adresa, i državljanstvo autora (grupe autora ili koautora), 
                    a ako su u pitanju jedan ili više autora koji nisu živi, imena autora i godine smrti autora, a ako je u pitanju autorsko delo anonimnog autora navod da je 
                    autorsko delo delo anonimnog autora:
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 200px" id="podaciOAutoruDetalji"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    9) Podaci da li je u pitanju autorsko delo stvoreno u radnom odnosu:
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="daLiJeRadniOdnos"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 30px">
                <h5>
                    10) Način korišćenja autorskog dela ili nameravani način korišćenja autorskog dela:
                </h5>

                <textarea class="form-control" style="margin-top: 20px; height: 100px" id="nacinKoriscenjaAutorskogDela"></textarea>
            </div>
            <div class="col-md-12" style="margin-top: 50px">
                <div class="row">
                    <div class="col-md-6">
                        <h5>
                            11)
                        </h5>
                    </div>
                    <div class="col-md-6">
                        <textarea class="form-control" style="margin-top: 20px; height: 50px" id="potpis"></textarea>
                        <h5 style="margin-top: 10px">Podnosilac prijave, nosilac prava</h5>
                        <h6>(mesto za potpis fizičkog lica, odnosno potpis zastupnika pravnog lica ili ovlašćenog predstavnika u pravnom licu)*</h6>
                    </div>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 40px">
                <h5>
                    12)  Prilozi koji se podnose uz zahtev
                </h5>

                @using (Html.BeginForm("UploadFiles", "AutorskaPrava", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input type="file" name="files" multiple />
                    <input type="submit" value="Upload" />
                }

                <label class="text-success" id="uploadSuccess" style="margin-top: 20px; display: none"><b>Fajlovi su uspešno dodati, nastavite sa prijavom.</b></label>
            </div>
            <div class="col-md-12 text-center" style="margin-top: 50px">
                <h5><b>POPUNJAVA ZAVOD</b> </h5>

                <div class="row">
                    <div class="col-md-12" style="text-align: left">
                        <br />
                        <br />
                        <h6><b>Prilozi uz prijavu: </b></h6>
                        <br />
                        <h6>opis autorskog dela (ako je delo podneto na optičkom disku); </h6>
                        <br />
                        <h6>primer autorskog dela (slika, video zapis, audio zapis); </h6>
                    </div>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 80px">
                <div class="row">
                    <div class="col-md-8"></div>
                    <div class="col-md-4" style="border: 1px solid black">
                        <div class="row">
                            <div class="col-md-12">
                                <h5>Broj prijave</h5>
                                <h4><b>A-</b></h4>
                                <hr />
                                <h5>Datum podnošenja: </h5>
                                <input type="date" class="form-control" id="datumPodnosenja"/>
                                <br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<h5>Rubrike u zahtevu A-1 koje su označene sa * moraju da budu obevezno popunjene.</h5>
<div class="row">
    <div class="col-md-12 float-end">
        <button class="btn btn-primary btn-lg btn-success" id="podnesiZahtev" onclick="AutorskoPravo.dodajPrijavu()">Podnesi zahtev</button>
        <label class="text-success" id="novaPrijavaSuccess" style="margin-top: 20px; display: none"><b>Prijava je uspešno dodata.</b></label>
    </div>
</div>